# This is a basic workflow that is manually triggered

name: GenerateZips

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:    
      - 'main'    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: make zips # run the run.py to get the latest data
            run: |
              python repo_generator.py
          - name: save zips
            uses: actions/upload-artifact@v2
            path: working-repo/
            
      
